<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DjTracksSessions.Api</RootNamespace>
    <AssemblyName>DjTracksSessions.Api</AssemblyName>
    <IsPackable>false</IsPackable>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <ProjectReference Include="..\DjTracksSessions.Contracts\DjTracksSessions.Contracts.csproj" />
  </ItemGroup>
</Project>
